[project]
name = "lend-contract"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.bitlend-core]
path = "contracts/bitlend-core.clar"
depends_on = []

[contracts.dao-governance]
path = "contracts/dao-governance.clar"
depends_on = []

[contracts.sbtc-collateral]
path = "contracts/sbtc-collateral.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
